https://github.com/KxSystems/kafka
sudo apt-get install librdkafka-dev
sudo apt-get install gcc-multilib

git clone https://github.com/edenhill/librdkafka.git

./configure --prefix=$HOME --disable-sasl --disable-lz4 --disable-ssl --mbits=32


